{-# LANGUAGE DamlSyntax #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleContexts #-}

module Example where

{-
This file contains an example of a DAML template which can be compiled, desugared, and type-check:
$ ./_build/stage1/bin/ghc ./Example.hs

A minimal environment (to support the code generated by desugaring) is provided in:
  ./libraries/base/DA/Internal/Desugar.hs

That module is part of the `base` library when building from the
`digital-asset/ghc` repository, and includes definitions from `daml-prim` and
`daml-stdlib` that would appear in other modules in the
`digital-asset/daml` repository, e.g. `GHC.Types`.{primitive, primitiveInterface}.

Since some of the generated code refers to types and values from `GHC.Types`,
we add `import qualified DA.Internal.Desugar as GHC.Types`.
-}

import DA.Internal.Desugar
import qualified DA.Internal.Desugar as GHC.Types

interface TheInterface where
  myInternalValue : Int
  viewtype Int

template TheTemplate
  with
    s : Party
  where
    signatory s
    agreement "my agreement"

    choice MyObservedChoice : () with obs : [Party]
      observer obs
      controller s
      do return ()

    interface instance TheInterface for TheTemplate where
      myInternalValue = 1000
      view = myInternalValue (toInterface @TheInterface this) * 1000

interface AnotherInterface where
  someBool : Bool
  viewtype Ordering

  interface instance AnotherInterface for TheTemplate where
    someBool = False
    view = if someBool (toInterface @AnotherInterface this) then GT else LT
